### ISSUE TITLE
UnicodeDecodeError on viewing markdown file with unicode characters

### ISSUE THREAD

**Issue by Erotemic** [guyru/mdview#3]
I was viewing a markdown file that contained unicode characters. This causes a UnicodeDecodeError in the markdown package: 

The error output is: 

```python
(venv2) joncrall@hyrule:~/latex/crall-thesis-2017$ mdview newchap4_outline.md 
 * Running on http://127.0.0.1:23269/ (Press CTRL+C to quit)
Created new window in existing browser session.
[2016-12-05 10:38:41,271] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/home/joncrall/venv2/local/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/joncrall/venv2/local/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/joncrall/venv2/local/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/joncrall/venv2/local/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/joncrall/venv2/local/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/joncrall/venv2/local/lib/python2.7/site-packages/mdview/__init__.py", line 25, in index
    html = markdown.markdown(source, extensions=app.config['extensions'])
  File "/home/joncrall/venv2/local/lib/python2.7/site-packages/markdown/__init__.py", line 494, in markdown
    return md.convert(text)
  File "/home/joncrall/venv2/local/lib/python2.7/site-packages/markdown/__init__.py", line 359, in convert
    source = util.text_type(source)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 2593: ordinal not in range(128). -- Note: Markdown only accepts unicode input!
```

To fix this I simply added this after line 23: 
```python
    source = source.decode('utf-8')
```

Not sure if this is a general fix, but I thought I'd post the issue.

**Comment by guyru** [comment]
Fixed in 2deb8aa
