### ISSUE TITLE
pip install seems broken in python3

### ISSUE THREAD

**Issue by Erotemic** [guyru/mdview#4]
I'm getting an error when installing mdview with pip3

```bash
(venv3) joncrall@hyrule:~/latex/crall-thesis-2017$ pip install mdview
Collecting mdview
  Using cached mdview-0.0.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-wnagj2o5/mdview/setup.py", line 23, in <module>
        version=get_version('mdview/__init__.py'),
      File "/tmp/pip-build-wnagj2o5/mdview/setup.py", line 19, in get_version
        return __version__
    NameError: name '__version__' is not defined

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-wnagj2o5/mdview/
```

My guess is that this is due to the expectation that __version__ is in globals.
 
You may be able to change 

```python
def get_version(filename):
    """Extract __version__ from file by parsing it."""
    with open(filename) as fp:
        for line in fp:
            if line.startswith('__version__'):
                exec(line,globals())
                return __version__

```

to 

```python
def get_version(filename):
    """Extract __version__ from file by parsing it."""
    with open(filename) as fp:
        for line in fp:
            if line.startswith('__version__'):
                namespace = {}
                exec(line, namespace)
                return namespace['__version__']
```

or you could even get away without doing any execs using this code: 

```python
def parse_version(filename):
    """ Statically parse the version number from __init__.py """
    import ast
    with open(filename) as file_:
        sourcecode = file_.read()
    pt = ast.parse(sourcecode)
    class VersionVisitor(ast.NodeVisitor):
        def visit_Assign(self, node):
            for target in node.targets:
                if target.id == '__version__':
                    self.version = node.value.s
    visitor = VersionVisitor()
    visitor.visit(pt)
    return visitor.version
```

**Comment by guyru** [comment]
This was actually fixed in PR #2. I need to push a new version to PyPI, meanwhile `mdview` can be installed directly from git.
